[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "ocDI"
version = "0.1.0"
dependencies = [
    "conllu==6.0.0",
    "datasets==4.4.2",
    "fasttext-numpy2==0.10.4",
    "ipywidgets>=8.0.0",
    "lxml>=6,<7",
    "matplotlib",
    "nltk>=3.9,<4",
    "notebook>=7.5.0,<8",
    "numpy==2.3.5",
    "pandas==2.3.3",
    "papermill==2.6.0",
    "regex>2025.10.23",
    "scikit-learn==1.7.2",
    "plotly>=6.5.0,<6.6.0",
    "python-slugify[unidecode]>=8.0.4,<8.1.0",
    "pyyaml>=6.0.3, <6.1.0",
    "requests>=2.32,<3",
    "tensorboard>=2.20.0,<2.21.0",
    "transformers[torch]>=4.57.0, <5.0.0",
    "tqdm>=4.67.1, <4.68",
    "occitok@git+https://github.com/DEFI-COLaF/occitok.git@v0.1.0"
]
requires-python = ">=3.11"
authors = [
    {name = "Oriane Nédey", email = "oriane.nedey@inria.fr"},
    {name = "Benoît Sagot"},
    {name = "Thibault Clérice"},
    {name = "Rachel Bawden"}
]

description = "Language identification experiments for Occitan varieties"
readme = "README.md"

[tool.setuptools.packages.find]
where = ["."]
include = ["ocdi*", "ocwikidialects/wisteps*"]
exclude = ["ocdi_scripts*"]
